/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LegalRouteImport } from './routes/_legal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppConversationRouteImport } from './routes/_app.conversation'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFaqRouteImport } from './routes/_app.faq'
import { Route as AppFeedbackRouteImport } from './routes/_app.feedback'
import { Route as AppListeningRouteImport } from './routes/_app.listening'
import { Route as AppPhrasebookRouteImport } from './routes/_app.phrasebook'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppReadingRouteImport } from './routes/_app.reading'
import { Route as LegalPrivacyRouteImport } from './routes/_legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/_legal.terms'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as BillingCanceledRouteImport } from './routes/billing.canceled'
import { Route as BillingSuccessRouteImport } from './routes/billing.success'
import { Route as UmamiSplatRouteImport } from './routes/umami.$'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminFeedbackRouteImport } from './routes/_app.admin.feedback'
import { Route as AppAdminReviewsRouteImport } from './routes/_app.admin.reviews'
import { Route as AppAdminSystemRouteImport } from './routes/_app.admin.system'
import { Route as AppAssessmentIndexRouteImport } from './routes/_app.assessment.index'
import { Route as AppAssessmentLevelTestRouteImport } from './routes/_app.assessment.level-test'
import { Route as AppFlashcardsIndexRouteImport } from './routes/_app.flashcards.index'
import { Route as AppFlashcardsVocabularyRouteImport } from './routes/_app.flashcards.vocabulary'
import { Route as AppGrammarIndexRouteImport } from './routes/_app.grammar.index'
import { Route as AppGrammarSlugRouteImport } from './routes/_app.grammar.$slug'
import { Route as AppLessonIdRouteImport } from './routes/_app.lesson.$id'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsLanguagesRouteImport } from './routes/_app.settings.languages'
import { Route as AppSettingsMemoriesRouteImport } from './routes/_app.settings.memories'
import { Route as AppVocabularyIndexRouteImport } from './routes/_app.vocabulary.index'
import { Route as AppVocabularySetIdRouteImport } from './routes/_app.vocabulary.$setId'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app.admin.users.index'
import { Route as AppAdminUsersIdRouteImport } from './routes/_app.admin.users.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/_legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationRoute = AppConversationRouteImport.update({
  id: '/conversation',
  path: '/conversation',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFaqRoute = AppFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppListeningRoute = AppListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AppRoute,
} as any)
const AppPhrasebookRoute = AppPhrasebookRouteImport.update({
  id: '/phrasebook',
  path: '/phrasebook',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingRoute = AppReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AppRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCanceledRoute = BillingCanceledRouteImport.update({
  id: '/billing/canceled',
  path: '/billing/canceled',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/billing/success',
  path: '/billing/success',
  getParentRoute: () => rootRouteImport,
} as any)
const UmamiSplatRoute = UmamiSplatRouteImport.update({
  id: '/umami/$',
  path: '/umami/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFeedbackRoute = AppAdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReviewsRoute = AppAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSystemRoute = AppAdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentIndexRoute = AppAssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentLevelTestRoute = AppAssessmentLevelTestRouteImport.update({
  id: '/assessment/level-test',
  path: '/assessment/level-test',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsIndexRoute = AppFlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => AppRoute,
} as any)
const AppFlashcardsVocabularyRoute = AppFlashcardsVocabularyRouteImport.update({
  id: '/flashcards/vocabulary',
  path: '/flashcards/vocabulary',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarIndexRoute = AppGrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => AppRoute,
} as any)
const AppGrammarSlugRoute = AppGrammarSlugRouteImport.update({
  id: '/grammar/$slug',
  path: '/grammar/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonIdRoute = AppLessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLanguagesRoute = AppSettingsLanguagesRouteImport.update({
  id: '/settings/languages',
  path: '/settings/languages',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMemoriesRoute = AppSettingsMemoriesRouteImport.update({
  id: '/settings/memories',
  path: '/settings/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularyIndexRoute = AppVocabularyIndexRouteImport.update({
  id: '/vocabulary/',
  path: '/vocabulary/',
  getParentRoute: () => AppRoute,
} as any)
const AppVocabularySetIdRoute = AppVocabularySetIdRouteImport.update({
  id: '/vocabulary/$setId',
  path: '/vocabulary/$setId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIdRoute = AppAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat': typeof AppChatRoute
  '/conversation': typeof AppConversationRoute
  '/dashboard': typeof AppDashboardRoute
  '/faq': typeof AppFaqRoute
  '/feedback': typeof AppFeedbackRoute
  '/listening': typeof AppListeningRoute
  '/phrasebook': typeof AppPhrasebookRoute
  '/plan': typeof AppPlanRoute
  '/progress': typeof AppProgressRoute
  '/reading': typeof AppReadingRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/umami/$': typeof UmamiSplatRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/reviews': typeof AppAdminReviewsRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/assessment/level-test': typeof AppAssessmentLevelTestRoute
  '/flashcards/vocabulary': typeof AppFlashcardsVocabularyRoute
  '/grammar/$slug': typeof AppGrammarSlugRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/settings/languages': typeof AppSettingsLanguagesRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/vocabulary/$setId': typeof AppVocabularySetIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/assessment/': typeof AppAssessmentIndexRoute
  '/flashcards/': typeof AppFlashcardsIndexRoute
  '/grammar/': typeof AppGrammarIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/vocabulary/': typeof AppVocabularyIndexRoute
  '/admin/users/$id': typeof AppAdminUsersIdRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/chat': typeof AppChatRoute
  '/conversation': typeof AppConversationRoute
  '/dashboard': typeof AppDashboardRoute
  '/faq': typeof AppFaqRoute
  '/feedback': typeof AppFeedbackRoute
  '/listening': typeof AppListeningRoute
  '/phrasebook': typeof AppPhrasebookRoute
  '/plan': typeof AppPlanRoute
  '/progress': typeof AppProgressRoute
  '/reading': typeof AppReadingRoute
  '/privacy': typeof LegalPrivacyRoute
  '/terms': typeof LegalTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/umami/$': typeof UmamiSplatRoute
  '/admin/feedback': typeof AppAdminFeedbackRoute
  '/admin/reviews': typeof AppAdminReviewsRoute
  '/admin/system': typeof AppAdminSystemRoute
  '/assessment/level-test': typeof AppAssessmentLevelTestRoute
  '/flashcards/vocabulary': typeof AppFlashcardsVocabularyRoute
  '/grammar/$slug': typeof AppGrammarSlugRoute
  '/lesson/$id': typeof AppLessonIdRoute
  '/settings/languages': typeof AppSettingsLanguagesRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/vocabulary/$setId': typeof AppVocabularySetIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/assessment': typeof AppAssessmentIndexRoute
  '/flashcards': typeof AppFlashcardsIndexRoute
  '/grammar': typeof AppGrammarIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/vocabulary': typeof AppVocabularyIndexRoute
  '/admin/users/$id': typeof AppAdminUsersIdRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_legal': typeof LegalRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/conversation': typeof AppConversationRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/faq': typeof AppFaqRoute
  '/_app/feedback': typeof AppFeedbackRoute
  '/_app/listening': typeof AppListeningRoute
  '/_app/phrasebook': typeof AppPhrasebookRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/reading': typeof AppReadingRoute
  '/_legal/privacy': typeof LegalPrivacyRoute
  '/_legal/terms': typeof LegalTermsRoute
  '/api/$': typeof ApiSplatRoute
  '/billing/canceled': typeof BillingCanceledRoute
  '/billing/success': typeof BillingSuccessRoute
  '/umami/$': typeof UmamiSplatRoute
  '/_app/admin/feedback': typeof AppAdminFeedbackRoute
  '/_app/admin/reviews': typeof AppAdminReviewsRoute
  '/_app/admin/system': typeof AppAdminSystemRoute
  '/_app/assessment/level-test': typeof AppAssessmentLevelTestRoute
  '/_app/flashcards/vocabulary': typeof AppFlashcardsVocabularyRoute
  '/_app/grammar/$slug': typeof AppGrammarSlugRoute
  '/_app/lesson/$id': typeof AppLessonIdRoute
  '/_app/settings/languages': typeof AppSettingsLanguagesRoute
  '/_app/settings/memories': typeof AppSettingsMemoriesRoute
  '/_app/vocabulary/$setId': typeof AppVocabularySetIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/assessment/': typeof AppAssessmentIndexRoute
  '/_app/flashcards/': typeof AppFlashcardsIndexRoute
  '/_app/grammar/': typeof AppGrammarIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/vocabulary/': typeof AppVocabularyIndexRoute
  '/_app/admin/users/$id': typeof AppAdminUsersIdRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/manifest.webmanifest'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify-email'
    | '/chat'
    | '/conversation'
    | '/dashboard'
    | '/faq'
    | '/feedback'
    | '/listening'
    | '/phrasebook'
    | '/plan'
    | '/progress'
    | '/reading'
    | '/privacy'
    | '/terms'
    | '/api/$'
    | '/billing/canceled'
    | '/billing/success'
    | '/umami/$'
    | '/admin/feedback'
    | '/admin/reviews'
    | '/admin/system'
    | '/assessment/level-test'
    | '/flashcards/vocabulary'
    | '/grammar/$slug'
    | '/lesson/$id'
    | '/settings/languages'
    | '/settings/memories'
    | '/vocabulary/$setId'
    | '/admin/'
    | '/assessment/'
    | '/flashcards/'
    | '/grammar/'
    | '/settings/'
    | '/vocabulary/'
    | '/admin/users/$id'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/manifest.webmanifest'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify-email'
    | '/chat'
    | '/conversation'
    | '/dashboard'
    | '/faq'
    | '/feedback'
    | '/listening'
    | '/phrasebook'
    | '/plan'
    | '/progress'
    | '/reading'
    | '/privacy'
    | '/terms'
    | '/api/$'
    | '/billing/canceled'
    | '/billing/success'
    | '/umami/$'
    | '/admin/feedback'
    | '/admin/reviews'
    | '/admin/system'
    | '/assessment/level-test'
    | '/flashcards/vocabulary'
    | '/grammar/$slug'
    | '/lesson/$id'
    | '/settings/languages'
    | '/settings/memories'
    | '/vocabulary/$setId'
    | '/admin'
    | '/assessment'
    | '/flashcards'
    | '/grammar'
    | '/settings'
    | '/vocabulary'
    | '/admin/users/$id'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_legal'
    | '/forgot-password'
    | '/login'
    | '/manifest.webmanifest'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify-email'
    | '/_app/chat'
    | '/_app/conversation'
    | '/_app/dashboard'
    | '/_app/faq'
    | '/_app/feedback'
    | '/_app/listening'
    | '/_app/phrasebook'
    | '/_app/plan'
    | '/_app/progress'
    | '/_app/reading'
    | '/_legal/privacy'
    | '/_legal/terms'
    | '/api/$'
    | '/billing/canceled'
    | '/billing/success'
    | '/umami/$'
    | '/_app/admin/feedback'
    | '/_app/admin/reviews'
    | '/_app/admin/system'
    | '/_app/assessment/level-test'
    | '/_app/flashcards/vocabulary'
    | '/_app/grammar/$slug'
    | '/_app/lesson/$id'
    | '/_app/settings/languages'
    | '/_app/settings/memories'
    | '/_app/vocabulary/$setId'
    | '/_app/admin/'
    | '/_app/assessment/'
    | '/_app/flashcards/'
    | '/_app/grammar/'
    | '/_app/settings/'
    | '/_app/vocabulary/'
    | '/_app/admin/users/$id'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiSplatRoute: typeof ApiSplatRoute
  BillingCanceledRoute: typeof BillingCanceledRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
  UmamiSplatRoute: typeof UmamiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_legal': {
      id: '/_legal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conversation': {
      id: '/_app/conversation'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof AppConversationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faq': {
      id: '/_app/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AppFaqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/feedback': {
      id: '/_app/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listening': {
      id: '/_app/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AppListeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/phrasebook': {
      id: '/_app/phrasebook'
      path: '/phrasebook'
      fullPath: '/phrasebook'
      preLoaderRoute: typeof AppPhrasebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading': {
      id: '/_app/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AppReadingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_legal/privacy': {
      id: '/_legal/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/_legal/terms': {
      id: '/_legal/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/canceled': {
      id: '/billing/canceled'
      path: '/billing/canceled'
      fullPath: '/billing/canceled'
      preLoaderRoute: typeof BillingCanceledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/billing/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umami/$': {
      id: '/umami/$'
      path: '/umami/$'
      fullPath: '/umami/$'
      preLoaderRoute: typeof UmamiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/feedback': {
      id: '/_app/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AppAdminFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reviews': {
      id: '/_app/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AppAdminReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/system': {
      id: '/_app/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AppAdminSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/': {
      id: '/_app/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AppAssessmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessment/level-test': {
      id: '/_app/assessment/level-test'
      path: '/assessment/level-test'
      fullPath: '/assessment/level-test'
      preLoaderRoute: typeof AppAssessmentLevelTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards/': {
      id: '/_app/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof AppFlashcardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flashcards/vocabulary': {
      id: '/_app/flashcards/vocabulary'
      path: '/flashcards/vocabulary'
      fullPath: '/flashcards/vocabulary'
      preLoaderRoute: typeof AppFlashcardsVocabularyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grammar/': {
      id: '/_app/grammar/'
      path: '/grammar'
      fullPath: '/grammar/'
      preLoaderRoute: typeof AppGrammarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grammar/$slug': {
      id: '/_app/grammar/$slug'
      path: '/grammar/$slug'
      fullPath: '/grammar/$slug'
      preLoaderRoute: typeof AppGrammarSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson/$id': {
      id: '/_app/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof AppLessonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/languages': {
      id: '/_app/settings/languages'
      path: '/settings/languages'
      fullPath: '/settings/languages'
      preLoaderRoute: typeof AppSettingsLanguagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/memories': {
      id: '/_app/settings/memories'
      path: '/settings/memories'
      fullPath: '/settings/memories'
      preLoaderRoute: typeof AppSettingsMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary/': {
      id: '/_app/vocabulary/'
      path: '/vocabulary'
      fullPath: '/vocabulary/'
      preLoaderRoute: typeof AppVocabularyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vocabulary/$setId': {
      id: '/_app/vocabulary/$setId'
      path: '/vocabulary/$setId'
      fullPath: '/vocabulary/$setId'
      preLoaderRoute: typeof AppVocabularySetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$id': {
      id: '/_app/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AppAdminUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppConversationRoute: typeof AppConversationRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFaqRoute: typeof AppFaqRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppListeningRoute: typeof AppListeningRoute
  AppPhrasebookRoute: typeof AppPhrasebookRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReadingRoute: typeof AppReadingRoute
  AppAdminFeedbackRoute: typeof AppAdminFeedbackRoute
  AppAdminReviewsRoute: typeof AppAdminReviewsRoute
  AppAdminSystemRoute: typeof AppAdminSystemRoute
  AppAssessmentLevelTestRoute: typeof AppAssessmentLevelTestRoute
  AppFlashcardsVocabularyRoute: typeof AppFlashcardsVocabularyRoute
  AppGrammarSlugRoute: typeof AppGrammarSlugRoute
  AppLessonIdRoute: typeof AppLessonIdRoute
  AppSettingsLanguagesRoute: typeof AppSettingsLanguagesRoute
  AppSettingsMemoriesRoute: typeof AppSettingsMemoriesRoute
  AppVocabularySetIdRoute: typeof AppVocabularySetIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAssessmentIndexRoute: typeof AppAssessmentIndexRoute
  AppFlashcardsIndexRoute: typeof AppFlashcardsIndexRoute
  AppGrammarIndexRoute: typeof AppGrammarIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppVocabularyIndexRoute: typeof AppVocabularyIndexRoute
  AppAdminUsersIdRoute: typeof AppAdminUsersIdRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppConversationRoute: AppConversationRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFaqRoute: AppFaqRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppListeningRoute: AppListeningRoute,
  AppPhrasebookRoute: AppPhrasebookRoute,
  AppPlanRoute: AppPlanRoute,
  AppProgressRoute: AppProgressRoute,
  AppReadingRoute: AppReadingRoute,
  AppAdminFeedbackRoute: AppAdminFeedbackRoute,
  AppAdminReviewsRoute: AppAdminReviewsRoute,
  AppAdminSystemRoute: AppAdminSystemRoute,
  AppAssessmentLevelTestRoute: AppAssessmentLevelTestRoute,
  AppFlashcardsVocabularyRoute: AppFlashcardsVocabularyRoute,
  AppGrammarSlugRoute: AppGrammarSlugRoute,
  AppLessonIdRoute: AppLessonIdRoute,
  AppSettingsLanguagesRoute: AppSettingsLanguagesRoute,
  AppSettingsMemoriesRoute: AppSettingsMemoriesRoute,
  AppVocabularySetIdRoute: AppVocabularySetIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAssessmentIndexRoute: AppAssessmentIndexRoute,
  AppFlashcardsIndexRoute: AppFlashcardsIndexRoute,
  AppGrammarIndexRoute: AppGrammarIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppVocabularyIndexRoute: AppVocabularyIndexRoute,
  AppAdminUsersIdRoute: AppAdminUsersIdRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LegalRouteChildren {
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiSplatRoute: ApiSplatRoute,
  BillingCanceledRoute: BillingCanceledRoute,
  BillingSuccessRoute: BillingSuccessRoute,
  UmamiSplatRoute: UmamiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
